# Generated by Django 4.2.7 on 2023-11-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('employer', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, choices=[('', '----Select----'), ('GP', 'GAUTENG'), ('MP', 'MPUMALANGA'), ('LP', 'LIMPOPO'), ('KZN', 'KWAZULU NATAL'), ('EC', 'EASTERN CAPE'), ('WC', 'WESTERN CAPE'), ('NC', 'NORTHEN CAPE'), ('NW', 'NORTH WEST'), ('FS', 'FREE STATE')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_work_here', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cellphone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('phone_number', models.CharField(blank=True, default='+27', max_length=13, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=4, null=True)),
                ('province', models.CharField(blank=True, choices=[('', '----Select----'), ('GP', 'GAUTENG'), ('MP', 'MPUMALANGA'), ('LP', 'LIMPOPO'), ('KZN', 'KWAZULU NATAL'), ('EC', 'EASTERN CAPE'), ('WC', 'WESTERN CAPE'), ('NC', 'NORTHEN CAPE'), ('NW', 'NORTH WEST'), ('FS', 'FREE STATE')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('', '----Select----'), ('ENG', 'English'), ('AFK', 'Afrikaans'), ('ZULU', 'IsiZulu'), ('SWATI', 'IsiSwati'), ('NDEBELE', 'Isindebele'), ('XHOSA', 'IsiXhosa'), ('VENDA', 'TshiVenda'), ('Tsonga', 'XiTsonga'), ('SOTHO', 'SeSotho'), ('PEDI', 'SePedi'), ('TSWANA', 'SeTswana')], max_length=50, null=True)),
                ('language_type', models.CharField(blank=True, choices=[('', '----Select----'), ('Home Language', 'Home Language'), ('First Additional Language', 'First Additional Language'), ('Second Additional Language', 'Second Additional Language'), ('Third Additional Language', 'Third Additional Language')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=50, null=True)),
                ('school_address', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('', '----Select----'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('National Senior Certificate', ' National Senior Certificate'), ('Higher certificate', 'Higher certificate'), ('National diploma', 'National diploma'), ("Bachelor's degree", "Bachelor's degree"), ('Honours degree', 'Honours degree'), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], max_length=50, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_graduation', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details')),
            ],
            options={
                'verbose_name': 'Educational Background',
                'verbose_name_plural': 'Educational Background',
            },
        ),
    ]
